version: '3.7'

services:
  qgis-server:
    # Should use version with utf-8 locale support:
    build: .
    volumes:
    - ./../resources:/data
    - ./../plugins_python:/home/qgis/plugins_python
    - ./../resources/profile_server:/home/qgis/profile_server
    networks:
      - qgis
    environment:
    - LANG=en_EN.UTF-8
    # - QGIS_PROJECT_FILE=/data/tests.qgs
    # - QGIS_PROJECT_FILE=/data/projects_ctxt/PLAPORT CONSULTA.qgs
    - QGIS_SERVER_LOG_LEVEL=0  # INFO (log all requests)
    - DEBUG=1                  # display env before spawning QGIS Server
    - QGIS_PLUGINPATH=/home/qgis/plugins_python
    - QGIS_OPTIONS_PATH=/home/qgis/data/profile_server
    - QGIS_SERVER_PARALLEL_RENDERING=true
    # - QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES=/data
  nginx:
    image: nginx:1.13
    ports:
    - 8080:80
    networks:
      - qgis
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./../resources/map.html:/usr/share/nginx/html/index.html:ro
    depends_on:
    - qgis-server

networks:
  qgis: {}
