@echo off

set QGIS_PREFIX_PATH=%OSGEO4W_ROOT:\=\%\apps\%QGISNAME%
set PATH=%OSGEO4W_ROOT%;%OSGEO4W_ROOT%\bin;%QGIS_PREFIX_PATH%;%QGIS_PREFIX_PATH%\bin;%PATH%
set GDAL_FILENAME_IS_UTF8=YES
set VSI_CACHE=TRUE
set VSI_CACHE_SIZE=1000000
set QT_PLUGIN_PATH=%QGIS_PREFIX_PATH%\qtplugins;%OSGEO4W_ROOT%\apps\qt4\plugins
set PYTHONPATH=%QGIS_PREFIX_PATH%\python;%PYTHONPATH%
